In [1]:
import numpy as np

In [2]:
x=np.array([1,5])

In [3]:
x+1

array([2, 6])

In [4]:
y=np.array([5,6])

In [5]:
x*y

array([ 5, 30])

In [6]:
x/y

array([0.2       , 0.83333333])

In [7]:
np.zeros([4,5])


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones([4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np.random.random([3,2])

array([[0.53114059, 0.07977077],
       [0.51479941, 0.77223286],
       [0.89575593, 0.03455828]])

In [10]:
A = np.random.random([n,1])

NameError: name 'n' is not defined

In [19]:
n=10
A = np.random.random([n,1])

In [11]:
x=np.array([3,5])

In [12]:
x.shape

(2,)

In [14]:
y=np.array([[3,5,1],[1,3,9]])

In [15]:
y.shape

(2, 3)

In [16]:
z=y.transpose

In [17]:
z

<function ndarray.transpose>

In [19]:
z=y.transpose()

In [20]:
z.shape

(3, 2)

In [21]:
z=y+3

In [22]:
z*y

array([[ 18,  40,   4],
       [  4,  18, 108]])

In [23]:
np.matmul(x,z)

array([38, 54, 72])

In [24]:
np.matmul(z,x)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [25]:
np.exp(x)

array([ 20.08553692, 148.4131591 ])

In [26]:
x

array([3, 5])

In [27]:
x=np.array([4,2,9,-6,5,11,3])

In [28]:
np.random.random([2,1])

array([[0.77721431],
       [0.38344005]])

In [30]:
np.random.random()

0.8966018449069384

In [31]:
np.linalg.norm(x)

17.08800749063506

In [33]:
np.random.random([5,1])

array([[0.62397789],
       [0.64524153],
       [0.35538866],
       [0.30008667],
       [0.09215007]])

In [2]:
range(3)

range(0, 3)

In [3]:
i=range(3)
i

range(0, 3)

In [4]:
print(i)

range(0, 3)


In [5]:
x = range(6)
for n in x:
  print(n)


0
1
2
3
4
5


In [6]:
metrics=[]

In [5]:
 metrics=[]
 i=0
 for i in range(3):
        metrics.append(lambda x: x + i)
